spring:
  datasource:

    url: jdbc:mysql://localhost:3306/train?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: eunseo
    password: "eunseo1018@"
    driver-class-name: com.mysql.cj.jdbc.Driver